### ISSUE TITLE
Rooms starting with special characters aren't grouped with their associated server

### ISSUE THREAD

**Issue by rodneyrod** [0x6d61676e7573/gtk-weechat#1]
System: Manjaro x86_64; Gnome Shell

Steps to reproduce:
1. Connect to a server
2. Join any room which contains an extra # at the start of the channel name, also applies to rooms that start with /

Expected behaviour: Rooms should be grouped with the server they're on

What happens: These overflow at the bottom of the server list.

May apply to other special characters but haven't tested that yet.

**Comment by 0x6d61676e7573** [comment]
Thanks for the report! I was not aware of the problem. It is fixed now.
